/* The phone layout.
 *
 *   node --test test/mobile.test.js
 *
 * There is no browser here, so this does not test that the drawer *slides* —
 * that was verified by rendering the app in headless Edge at 390px and clicking
 * the control. What it holds are the two invariants that are easy to break by
 * editing one file and not the other, and that fail silently when broken.
 *
 * The shell is a two-column flex whose widths are inline `style` attributes on
 * generated markup, so the mobile layer lives in app.css and the trigger is
 * injected at runtime by app-ui.js. Neither file can see the other, which is
 * exactly why they need a test between them.
 */

const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('fs');
const path = require('path');

const asset = (name) => fs.readFileSync(path.join(__dirname, '..', 'public', 'assets', name), 'utf8');

const CSS = asset('app.css');
const JS = asset('app-ui.js');

/* Everything inside the phone breakpoint, and everything outside it. */
const MOBILE = (() => {
  const at = CSS.indexOf('@media (max-width: 860px)');
  assert.ok(at > -1, 'the phone breakpoint is gone from app.css');
  let depth = 0;
  let i = CSS.indexOf('{', at);
  const start = i;
  for (; i < CSS.length; i += 1) {
    if (CSS[i] === '{') depth += 1;
    else if (CSS[i] === '}') { depth -= 1; if (!depth) break; }
  }
  return { inside: CSS.slice(start, i), outside: CSS.slice(0, at) + CSS.slice(i) };
})();

test('the drawer trigger is hidden until the breakpoint asks for it', () => {
  /* The regression this exists for, which shipped once in a screenshot: the
     button is injected on every page load because app-ui.js runs once and does
     not watch the viewport. Styled only inside the media query, it renders on a
     desktop as an unstyled browser button in the top bar. */
  assert.match(MOBILE.outside, /\.li-navbtn\s*\{[^}]*display:\s*none/,
    '.li-navbtn has no base display:none, so it shows on desktop');
  assert.match(MOBILE.inside, /\.li-navbtn\s*\{[^}]*display:\s*grid/,
    '.li-navbtn is never shown inside the breakpoint, so the drawer cannot be opened');
});

test('the sidebar leaves the flow on a phone, and beats the inline width', () => {
  /* Measured before the change: 214px of a 390px screen, 55% of it, with the
     dashboard rendering into the 176px left over. The width is an inline style
     attribute on generated markup, so nothing but !important can move it. */
  assert.match(MOBILE.inside, /\.app > nav\s*\{[^}]*position:\s*fixed/,
    'the sidebar still takes part in the flex row on a phone');
  assert.match(MOBILE.inside, /\.app > nav\s*\{[^}]*width:[^;]*!important/,
    'the width does not override the inline style attribute, so the drawer keeps the desktop width');
});

test('the drawer is out of the tab order while it is shut', () => {
  /* Thirteen links a keyboard or screen reader would walk through on every
     screen, over content they cannot see. `transform` alone does not remove
     them; `visibility` does. */
  assert.match(MOBILE.inside, /\.app > nav\s*\{[^}]*visibility:\s*hidden/);
  assert.match(MOBILE.inside, /\.li-nav-open > nav\s*\{[^}]*visibility:\s*visible/);
});

test('the runtime injects the trigger rather than the markup carrying it', () => {
  /* views/ is generated by tools/dc-to-ejs.js, so a hand-added button would be
     dropped by the next conversion — the same reason the filter chips are
     enhanced in place. */
  assert.match(JS, /function enhanceMobileNav\(\)/);
  assert.match(JS, /enhanceMobileNav\(\);/, 'the enhancer is defined and never called');
  assert.match(JS, /className = 'li-navbtn'/, 'the injected button does not carry the class the stylesheet targets');

  const views = path.join(__dirname, '..', 'views');
  const walk = (dir) => fs.readdirSync(dir, { withFileTypes: true }).flatMap((e) => (
    e.isDirectory() ? walk(path.join(dir, e.name)) : [path.join(dir, e.name)]
  ));
  const offenders = walk(views).filter((f) => f.endsWith('.ejs') && fs.readFileSync(f, 'utf8').includes('li-navbtn'));
  assert.deepEqual(offenders, [], 'a generated view carries the trigger, which the next conversion would drop');
});

test('the class that opens the drawer goes on the shell, not the nav', () => {
  /* So the stylesheet decides what "open" means — today a transform and a
     scrim, tomorrow whatever suits — without app-ui.js having to know. */
  assert.match(JS, /app\.classList\.toggle\('li-nav-open'/);
  assert.match(MOBILE.inside, /\.app\.li-nav-open > nav/);
});

test('closing is possible by every route a phone offers', () => {
  /* A drawer with no way back is worse than no drawer. Tapping outside it,
     Escape, and following a link — the last because a drawer left open over the
     page it just loaded reads as a broken back button. */
  assert.match(JS, /Escape/);
  assert.match(JS, /nav\.contains\(e\.target\)/, 'a tap outside the drawer does not close it');
  assert.match(JS, /nav\.addEventListener\('click'/, 'following a link leaves the drawer open over the new page');
});
